- name: Sending an e-mail using Gmail SMTP servers
  mail:
    host: smtp.gmail.com
    port: 587
    secure: starttls
    charset: utf-8
    sender: ybmadhuit@gmail.com
    username: ybmadhuit@gmail.com
    password: "{{ password }}"
    to: ybmadhu404@gmail.com
    subject: Ansible-report
    body: veresion comparision "{{ ansible_distribution_version is version('7', '>=') }}"

